# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Tester_AKB.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_Tester_AKB(object):
    def setupUi(self, Form_Tester_AKB):
        Form_Tester_AKB.setObjectName("Form_Tester_AKB")
        Form_Tester_AKB.resize(383, 629)
        Form_Tester_AKB.setMinimumSize(QtCore.QSize(383, 629))
        Form_Tester_AKB.setMaximumSize(QtCore.QSize(383, 629))
        Form_Tester_AKB.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("75.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_Tester_AKB.setWindowIcon(icon)
        Form_Tester_AKB.setAnimated(True)
        Form_Tester_AKB.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(Form_Tester_AKB)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Baudrate.setGeometry(QtCore.QRect(89, 28, 74, 20))
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.comboBox_COM = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_COM.setGeometry(QtCore.QRect(9, 28, 74, 20))
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.label_change_port = QtWidgets.QLabel(self.centralwidget)
        self.label_change_port.setGeometry(QtCore.QRect(9, 9, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_change_port.setFont(font)
        self.label_change_port.setObjectName("label_change_port")
        self.pushButton_open_COM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_COM.setGeometry(QtCore.QRect(169, 27, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_open_COM.setFont(font)
        self.pushButton_open_COM.setObjectName("pushButton_open_COM")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(150, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_main.setFont(font)
        self.label_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_main.setStyleSheet("")
        self.label_main.setObjectName("label_main")
        self.pushButton_Clear_Channels = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Clear_Channels.setEnabled(False)
        self.pushButton_Clear_Channels.setGeometry(QtCore.QRect(90, 308, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Clear_Channels.setFont(font)
        self.pushButton_Clear_Channels.setObjectName("pushButton_Clear_Channels")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(10, 80, 160, 20))
        self.frame_1.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_t1 = QtWidgets.QLabel(self.frame_1)
        self.label_t1.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t1.setFont(font)
        self.label_t1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t1.setStyleSheet("")
        self.label_t1.setObjectName("label_t1")
        self.label_1 = QtWidgets.QLabel(self.frame_1)
        self.label_1.setGeometry(QtCore.QRect(12, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_1.setStyleSheet("")
        self.label_1.setObjectName("label_1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 160, 20))
        self.frame_2.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_t2 = QtWidgets.QLabel(self.frame_2)
        self.label_t2.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t2.setFont(font)
        self.label_t2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t2.setStyleSheet("")
        self.label_t2.setObjectName("label_t2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(12, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 120, 160, 20))
        self.frame_3.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_t3 = QtWidgets.QLabel(self.frame_3)
        self.label_t3.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t3.setFont(font)
        self.label_t3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t3.setStyleSheet("")
        self.label_t3.setObjectName("label_t3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(12, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 140, 160, 20))
        self.frame_4.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_t4 = QtWidgets.QLabel(self.frame_4)
        self.label_t4.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t4.setFont(font)
        self.label_t4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t4.setStyleSheet("")
        self.label_t4.setObjectName("label_t4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(13, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 160, 160, 20))
        self.frame_5.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_t5 = QtWidgets.QLabel(self.frame_5)
        self.label_t5.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t5.setFont(font)
        self.label_t5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t5.setStyleSheet("")
        self.label_t5.setObjectName("label_t5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(10, 180, 160, 20))
        self.frame_6.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_t6 = QtWidgets.QLabel(self.frame_6)
        self.label_t6.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t6.setFont(font)
        self.label_t6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t6.setStyleSheet("")
        self.label_t6.setObjectName("label_t6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(10, 200, 160, 20))
        self.frame_7.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_t7 = QtWidgets.QLabel(self.frame_7)
        self.label_t7.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t7.setFont(font)
        self.label_t7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t7.setStyleSheet("")
        self.label_t7.setObjectName("label_t7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(10, 220, 160, 20))
        self.frame_8.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_t8 = QtWidgets.QLabel(self.frame_8)
        self.label_t8.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t8.setFont(font)
        self.label_t8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t8.setStyleSheet("")
        self.label_t8.setObjectName("label_t8")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(10, 240, 160, 20))
        self.frame_9.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_t9 = QtWidgets.QLabel(self.frame_9)
        self.label_t9.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t9.setFont(font)
        self.label_t9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t9.setStyleSheet("")
        self.label_t9.setObjectName("label_t9")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(10, 260, 160, 20))
        self.frame_10.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_t10 = QtWidgets.QLabel(self.frame_10)
        self.label_t10.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t10.setFont(font)
        self.label_t10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t10.setStyleSheet("")
        self.label_t10.setObjectName("label_t10")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(13, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(180, 140, 160, 20))
        self.frame_14.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_t14 = QtWidgets.QLabel(self.frame_14)
        self.label_t14.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t14.setFont(font)
        self.label_t14.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t14.setStyleSheet("")
        self.label_t14.setObjectName("label_t14")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setGeometry(QtCore.QRect(180, 160, 160, 20))
        self.frame_15.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_t15 = QtWidgets.QLabel(self.frame_15)
        self.label_t15.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t15.setFont(font)
        self.label_t15.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t15.setStyleSheet("")
        self.label_t15.setObjectName("label_t15")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setGeometry(QtCore.QRect(180, 120, 160, 20))
        self.frame_13.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_t13 = QtWidgets.QLabel(self.frame_13)
        self.label_t13.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t13.setFont(font)
        self.label_t13.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t13.setStyleSheet("")
        self.label_t13.setObjectName("label_t13")
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        self.label_13.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(180, 180, 160, 20))
        self.frame_16.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_t16 = QtWidgets.QLabel(self.frame_16)
        self.label_t16.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t16.setFont(font)
        self.label_t16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t16.setStyleSheet("")
        self.label_t16.setObjectName("label_t16")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        self.label_16.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(180, 80, 160, 20))
        self.frame_11.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_t11 = QtWidgets.QLabel(self.frame_11)
        self.label_t11.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t11.setFont(font)
        self.label_t11.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t11.setStyleSheet("")
        self.label_t11.setObjectName("label_t11")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setGeometry(QtCore.QRect(180, 100, 160, 20))
        self.frame_12.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_t12 = QtWidgets.QLabel(self.frame_12)
        self.label_t12.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t12.setFont(font)
        self.label_t12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t12.setStyleSheet("")
        self.label_t12.setObjectName("label_t12")
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.frame_19 = QtWidgets.QFrame(self.centralwidget)
        self.frame_19.setGeometry(QtCore.QRect(180, 240, 160, 20))
        self.frame_19.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_t19 = QtWidgets.QLabel(self.frame_19)
        self.label_t19.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t19.setFont(font)
        self.label_t19.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t19.setStyleSheet("")
        self.label_t19.setObjectName("label_t19")
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        self.label_19.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setGeometry(QtCore.QRect(180, 200, 160, 20))
        self.frame_17.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_t17 = QtWidgets.QLabel(self.frame_17)
        self.label_t17.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t17.setFont(font)
        self.label_t17.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t17.setStyleSheet("")
        self.label_t17.setObjectName("label_t17")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.frame_18 = QtWidgets.QFrame(self.centralwidget)
        self.frame_18.setGeometry(QtCore.QRect(180, 220, 160, 20))
        self.frame_18.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_t18 = QtWidgets.QLabel(self.frame_18)
        self.label_t18.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t18.setFont(font)
        self.label_t18.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t18.setStyleSheet("")
        self.label_t18.setObjectName("label_t18")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        self.label_18.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.pushButton_close_COM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close_COM.setEnabled(False)
        self.pushButton_close_COM.setGeometry(QtCore.QRect(265, 27, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_close_COM.setFont(font)
        self.pushButton_close_COM.setObjectName("pushButton_close_COM")
        self.pushButton_Start_Polling = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start_Polling.setEnabled(False)
        self.pushButton_Start_Polling.setGeometry(QtCore.QRect(10, 340, 201, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Start_Polling.setFont(font)
        self.pushButton_Start_Polling.setObjectName("pushButton_Start_Polling")
        self.comboBox_Clear_Channels = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Clear_Channels.setEnabled(False)
        self.comboBox_Clear_Channels.setGeometry(QtCore.QRect(10, 310, 74, 20))
        self.comboBox_Clear_Channels.setObjectName("comboBox_Clear_Channels")
        self.label_main_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_main_2.setGeometry(QtCore.QRect(10, 290, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_main_2.setFont(font)
        self.label_main_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_main_2.setStyleSheet("")
        self.label_main_2.setObjectName("label_main_2")
        self.pushButton_Stop_Polling = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop_Polling.setEnabled(False)
        self.pushButton_Stop_Polling.setGeometry(QtCore.QRect(10, 365, 201, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Stop_Polling.setFont(font)
        self.pushButton_Stop_Polling.setObjectName("pushButton_Stop_Polling")
        self.pushButton_Set_Params = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set_Params.setEnabled(False)
        self.pushButton_Set_Params.setGeometry(QtCore.QRect(90, 560, 201, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Set_Params.setFont(font)
        self.pushButton_Set_Params.setObjectName("pushButton_Set_Params")
        self.comboBox_Rele_Number = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Rele_Number.setEnabled(False)
        self.comboBox_Rele_Number.setGeometry(QtCore.QRect(20, 410, 71, 20))
        self.comboBox_Rele_Number.setObjectName("comboBox_Rele_Number")
        self.label_Rele_Number = QtWidgets.QLabel(self.centralwidget)
        self.label_Rele_Number.setGeometry(QtCore.QRect(100, 410, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Rele_Number.setFont(font)
        self.label_Rele_Number.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Rele_Number.setStyleSheet("")
        self.label_Rele_Number.setObjectName("label_Rele_Number")
        self.comboBox_Rele_Contr_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Rele_Contr_1.setEnabled(False)
        self.comboBox_Rele_Contr_1.setGeometry(QtCore.QRect(20, 440, 71, 20))
        self.comboBox_Rele_Contr_1.setObjectName("comboBox_Rele_Contr_1")
        self.label_Rele_Contr_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Rele_Contr_1.setGeometry(QtCore.QRect(100, 440, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Rele_Contr_1.setFont(font)
        self.label_Rele_Contr_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Rele_Contr_1.setStyleSheet("")
        self.label_Rele_Contr_1.setObjectName("label_Rele_Contr_1")
        self.label_Rele_Contr_All = QtWidgets.QLabel(self.centralwidget)
        self.label_Rele_Contr_All.setGeometry(QtCore.QRect(100, 470, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Rele_Contr_All.setFont(font)
        self.label_Rele_Contr_All.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Rele_Contr_All.setStyleSheet("")
        self.label_Rele_Contr_All.setObjectName("label_Rele_Contr_All")
        self.comboBox_Rele_Contr_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Rele_Contr_2.setEnabled(False)
        self.comboBox_Rele_Contr_2.setGeometry(QtCore.QRect(20, 470, 71, 20))
        self.comboBox_Rele_Contr_2.setObjectName("comboBox_Rele_Contr_2")
        self.radioButton_First_Rele = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_First_Rele.setEnabled(False)
        self.radioButton_First_Rele.setGeometry(QtCore.QRect(20, 500, 351, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_First_Rele.setFont(font)
        self.radioButton_First_Rele.setChecked(True)
        self.radioButton_First_Rele.setObjectName("radioButton_First_Rele")
        self.radioButton_All_Rele = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_All_Rele.setEnabled(False)
        self.radioButton_All_Rele.setGeometry(QtCore.QRect(20, 530, 351, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_All_Rele.setFont(font)
        self.radioButton_All_Rele.setObjectName("radioButton_All_Rele")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 400, 371, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox_Time_Charge = QtWidgets.QComboBox(self.frame)
        self.comboBox_Time_Charge.setEnabled(False)
        self.comboBox_Time_Charge.setGeometry(QtCore.QRect(160, 10, 71, 20))
        self.comboBox_Time_Charge.setObjectName("comboBox_Time_Charge")
        self.label_Time_Charge = QtWidgets.QLabel(self.frame)
        self.label_Time_Charge.setGeometry(QtCore.QRect(236, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Time_Charge.setFont(font)
        self.label_Time_Charge.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Time_Charge.setStyleSheet("")
        self.label_Time_Charge.setObjectName("label_Time_Charge")
        self.frame_20 = QtWidgets.QFrame(self.centralwidget)
        self.frame_20.setGeometry(QtCore.QRect(180, 260, 160, 20))
        self.frame_20.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_t20 = QtWidgets.QLabel(self.frame_20)
        self.label_t20.setGeometry(QtCore.QRect(45, 2, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t20.setFont(font)
        self.label_t20.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t20.setStyleSheet("")
        self.label_t20.setObjectName("label_t20")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.frame_21 = QtWidgets.QFrame(self.centralwidget)
        self.frame_21.setGeometry(QtCore.QRect(220, 340, 160, 20))
        self.frame_21.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_t21 = QtWidgets.QLabel(self.frame_21)
        self.label_t21.setGeometry(QtCore.QRect(80, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t21.setFont(font)
        self.label_t21.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t21.setStyleSheet("")
        self.label_t21.setObjectName("label_t21")
        self.label_21 = QtWidgets.QLabel(self.frame_21)
        self.label_21.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.frame_22 = QtWidgets.QFrame(self.centralwidget)
        self.frame_22.setGeometry(QtCore.QRect(220, 366, 160, 20))
        self.frame_22.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_t22 = QtWidgets.QLabel(self.frame_22)
        self.label_t22.setGeometry(QtCore.QRect(80, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t22.setFont(font)
        self.label_t22.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t22.setStyleSheet("")
        self.label_t22.setObjectName("label_t22")
        self.label_22 = QtWidgets.QLabel(self.frame_22)
        self.label_22.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_22.setStyleSheet("")
        self.label_22.setObjectName("label_22")
        self.frame.raise_()
        self.frame_18.raise_()
        self.frame_19.raise_()
        self.frame_17.raise_()
        self.frame_16.raise_()
        self.frame_12.raise_()
        self.frame_15.raise_()
        self.frame_11.raise_()
        self.frame_13.raise_()
        self.frame_14.raise_()
        self.frame_6.raise_()
        self.frame_5.raise_()
        self.frame_10.raise_()
        self.frame_7.raise_()
        self.frame_9.raise_()
        self.frame_8.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.frame_1.raise_()
        self.comboBox_Baudrate.raise_()
        self.comboBox_COM.raise_()
        self.label_change_port.raise_()
        self.pushButton_open_COM.raise_()
        self.label_main.raise_()
        self.pushButton_Clear_Channels.raise_()
        self.pushButton_close_COM.raise_()
        self.pushButton_Start_Polling.raise_()
        self.comboBox_Clear_Channels.raise_()
        self.label_main_2.raise_()
        self.pushButton_Stop_Polling.raise_()
        self.pushButton_Set_Params.raise_()
        self.comboBox_Rele_Number.raise_()
        self.label_Rele_Number.raise_()
        self.comboBox_Rele_Contr_1.raise_()
        self.label_Rele_Contr_1.raise_()
        self.label_Rele_Contr_All.raise_()
        self.comboBox_Rele_Contr_2.raise_()
        self.radioButton_First_Rele.raise_()
        self.radioButton_All_Rele.raise_()
        self.frame_20.raise_()
        self.frame_21.raise_()
        self.frame_22.raise_()
        Form_Tester_AKB.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_Tester_AKB)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 18))
        self.menubar.setObjectName("menubar")
        Form_Tester_AKB.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_Tester_AKB)
        self.statusbar.setObjectName("statusbar")
        Form_Tester_AKB.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Form_Tester_AKB)
        self.action.setObjectName("action")

        self.retranslateUi(Form_Tester_AKB)
        QtCore.QMetaObject.connectSlotsByName(Form_Tester_AKB)

    def retranslateUi(self, Form_Tester_AKB):
        _translate = QtCore.QCoreApplication.translate
        Form_Tester_AKB.setWindowTitle(_translate("Form_Tester_AKB", "Тестер аккумуляторов"))
        self.label_change_port.setText(_translate("Form_Tester_AKB", "Выбор порта"))
        self.pushButton_open_COM.setText(_translate("Form_Tester_AKB", "Открыть порт"))
        self.label_main.setText(_translate("Form_Tester_AKB", "Входы"))
        self.pushButton_Clear_Channels.setText(_translate("Form_Tester_AKB", "Обнулить счетчик"))
        self.label_t1.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_1.setText(_translate("Form_Tester_AKB", "№1"))
        self.label_t2.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_2.setText(_translate("Form_Tester_AKB", "№2"))
        self.label_t3.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_3.setText(_translate("Form_Tester_AKB", "№3"))
        self.label_t4.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_4.setText(_translate("Form_Tester_AKB", "№4"))
        self.label_t5.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_5.setText(_translate("Form_Tester_AKB", "№5"))
        self.label_t6.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_6.setText(_translate("Form_Tester_AKB", "№6"))
        self.label_t7.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_7.setText(_translate("Form_Tester_AKB", "№7"))
        self.label_t8.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_8.setText(_translate("Form_Tester_AKB", "№8"))
        self.label_t9.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_9.setText(_translate("Form_Tester_AKB", "№9"))
        self.label_t10.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_10.setText(_translate("Form_Tester_AKB", "№10"))
        self.label_t14.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_14.setText(_translate("Form_Tester_AKB", "№14"))
        self.label_t15.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_15.setText(_translate("Form_Tester_AKB", "№15"))
        self.label_t13.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_13.setText(_translate("Form_Tester_AKB", "№13"))
        self.label_t16.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_16.setText(_translate("Form_Tester_AKB", "№16"))
        self.label_t11.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_11.setText(_translate("Form_Tester_AKB", "№11"))
        self.label_t12.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_12.setText(_translate("Form_Tester_AKB", "№12"))
        self.label_t19.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_19.setText(_translate("Form_Tester_AKB", "№19"))
        self.label_t17.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_17.setText(_translate("Form_Tester_AKB", "№17"))
        self.label_t18.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_18.setText(_translate("Form_Tester_AKB", "№18"))
        self.pushButton_close_COM.setText(_translate("Form_Tester_AKB", "Закрыть порт"))
        self.pushButton_Start_Polling.setText(_translate("Form_Tester_AKB", "Начать опрос каналов"))
        self.label_main_2.setText(_translate("Form_Tester_AKB", "№ канала"))
        self.pushButton_Stop_Polling.setText(_translate("Form_Tester_AKB", "Остановить опрос каналов"))
        self.pushButton_Set_Params.setText(_translate("Form_Tester_AKB", "Задать параметры"))
        self.label_Rele_Number.setText(_translate("Form_Tester_AKB", "№ реле"))
        self.label_Rele_Contr_1.setText(_translate("Form_Tester_AKB", "канал под контролем"))
        self.label_Rele_Contr_All.setText(_translate("Form_Tester_AKB", "канал под контролем"))
        self.radioButton_First_Rele.setText(_translate("Form_Tester_AKB", "Включение реле по первому разрядившемуся"))
        self.radioButton_All_Rele.setText(_translate("Form_Tester_AKB", "Включение реле, когда разрядились все каналы"))
        self.label_Time_Charge.setText(_translate("Form_Tester_AKB", "Время заряда, час"))
        self.label_t20.setText(_translate("Form_Tester_AKB", "выключен"))
        self.label_20.setText(_translate("Form_Tester_AKB", "№20"))
        self.label_t21.setText(_translate("Form_Tester_AKB", "выключено"))
        self.label_21.setText(_translate("Form_Tester_AKB", "Реле №1"))
        self.label_t22.setText(_translate("Form_Tester_AKB", "выключено"))
        self.label_22.setText(_translate("Form_Tester_AKB", "Реле №2"))
        self.action.setText(_translate("Form_Tester_AKB", "Закрыть"))

